using System.Collections.Generic;
using System.Text;

namespace YARG.Menu.Career.CoverFlow
{
    /// <summary>
    /// Static utility that maps emoji characters to TMP sprite names for the
    /// HypeEngine card text. Converts emoji-bearing strings like "👑 FINAL BOSS"
    /// into TMP-tagged strings like "<sprite name=crown> FINAL BOSS".
    ///
    /// The sprite names correspond to the SVG icons compiled by
    /// HypeSpriteAssetGenerator into HypeIcons_SpriteAsset.asset.
    ///
    /// Usage:
    ///   string tagged = EmojiSpriteMapper.ReplaceEmojis(rawHypeText);
    ///   myTmpText.text = tagged;
    ///   // Ensure myTmpText has HypeIcons_SpriteAsset assigned as a fallback
    ///   // or primary sprite asset.
    /// </summary>
    public static class EmojiSpriteMapper
    {
        // ── Emoji → Sprite Name Mapping ──────────────────────────

        /// <summary>
        /// Maps Unicode emoji codepoints to the sprite names generated by
        /// HypeSpriteAssetGenerator (derived from SVG filenames in solo/).
        /// </summary>
        private static readonly Dictionary<string, string> s_emojiToSprite = new()
        {
            // Tier 1 — Campaign Proximity & Milestones
            { "\U0001F451", "crown"      },  // 👑 CampaignFinale
            { "\U0001F525", "fire"       },  // 🔥 CampaignFinale, HeadlinerHook
            { "\U0001F3B8", "guitar"     },  // 🎸 VenueGate
            { "\U0001F3C1", "flag"       },  // 🏁 CampaignPenultimate
            { "\U0001F3AB", "ticket"     },  // 🎫 VenuePenultimate
            { "\U0001F3C6", "trophy"     },  // 🏆 CampaignEndgamePush, HeadlinerShowdown
            { "\U0001F522", "numbers"    },  // 🔢 SingleDigitCampaign
            { "\U0001F50B", "battery"    },  // 🔋 MidCampaignDrive

            // Tier 2 — Time-Efficiency & Low-Friction
            { "\U0001F3C3", "running"    },  // 🏃 MicroSprint
            { "\u26A1",    "lightning"   },  // ⚡ BlitzPlay, QuickThreeTrack, MidwayMarathonMitigation
            { "\U0001F6F9", "skateboard" },  // 🛹 PunkRockBlitz
            { "\u23F1",    "stopwatch"   },  // ⏱️ UnderTenClub, BiteSized

            // Tier 3 — Icon Worship & FOMO
            { "\u2B50",    "star"        },  // ⭐ HeadlinerFastTrack
            { "\U0001F4E3", "megaphone"  },  // 📣 ArenaDemand
            { "\U0001F4FB", "radio"      },  // 📻 RadioGold

            // Tier 4 — Stamina Mitigation & Casual Flow
            { "\U0001F9D8", "yoga"       },  // 🧘 SmoothSailing
            { "\U0001F60E", "sunglasses" },  // 😎 StaminaMitigation
            { "\U0001F343", "leaf"       },  // 🍃 ComedownSet
            { "\U0001F6E1", "shield"     },  // 🛡️ RecoveryTracks

            // Tier 5 — Structural Safety Nets
            { "\U0001F331", "sprout"     },  // 🌱 EarlyCampaignSprint
            { "\U0001F9F9", "broom"      },  // 🧹 TierCleanOut
            { "\U0001F4C8", "chart_up"   },  // 📈 TierHalfway

            // Tier 0 / Fallback & Unlock
            { "\U0001F512", "shield"     },  // 🔒 Lock icon → shield (closest match)
            { "\U0001F3AF", "star"       },  // 🎯 → star (no direct match)
            { "\U0001F3B5", "audio"      },  // 🎵 → audio
            { "\U0001F3A4", "audio"      },  // 🎤 → audio (no direct match)
            { "\U0001F680", "rocket"     },  // 🚀 → rocket
            { "\U0001F4CC", "pin"        },  // 📌 → pin
        };

        // ── Cached StringBuilder (reused to avoid GC) ────────────

        private static StringBuilder s_builder;

        // ── Public API ────────────────────────────────────────────

        /// <summary>
        /// Scans <paramref name="text"/> for known emoji characters and replaces
        /// each with a <c><sprite name="..."></c> TMP tag. Unknown emojis
        /// and non-emoji text pass through unchanged.
        ///
        /// Returns the original string if no replacements were made (zero allocation).
        /// </summary>
        public static string ReplaceEmojis(string text)
        {
            if (string.IsNullOrEmpty(text))
                return text;

            // Fast path: scan for any known emoji before allocating
            bool hasMatch = false;
            foreach (var kvp in s_emojiToSprite)
            {
                if (text.Contains(kvp.Key))
                {
                    hasMatch = true;
                    break;
                }
            }

            if (!hasMatch)
                return text;

            // Slow path: perform replacements
            var sb = s_builder ?? new StringBuilder(text.Length + 64);
            sb.Clear();
            s_builder = sb;

            int i = 0;
            while (i < text.Length)
            {
                bool replaced = false;

                // Check each emoji mapping (longest match first to avoid partial matches)
                foreach (var kvp in s_emojiToSprite)
                {
                    if (i + kvp.Key.Length <= text.Length &&
                        string.CompareOrdinal(text, i, kvp.Key, 0, kvp.Key.Length) == 0)
                    {
                        sb.Append("<sprite name=");
                        sb.Append(kvp.Value);
                        sb.Append('>');
                        i += kvp.Key.Length;
                        replaced = true;
                        break;
                    }
                }

                if (!replaced)
                {
                    // Check for surrogate pairs (other emojis we don't map)
                    if (char.IsHighSurrogate(text[i]) && i + 1 < text.Length &&
                        char.IsLowSurrogate(text[i + 1]))
                    {
                        // Pass through unmapped emoji as-is (TMP may render it natively)
                        sb.Append(text[i]);
                        sb.Append(text[i + 1]);
                        i += 2;
                    }
                    else
                    {
                        sb.Append(text[i]);
                        i++;
                    }
                }
            }

            return sb.ToString();
        }
    }
}